POST http://localhost:8000/api/v1/auth/register
Accept: application/json
Content-Type: application/json

{
    "name": "admin2",
    "email": "admin@gmail.com",
    "password": "admin123",
    "password2": "admin123"
}

### 1. login Iniciar Sesión como Super Admin
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "jugadordeunbit@gmail.com",
    "password": "jugadordeunbit5011070"
}
### Cambiar Contraseña Inicial
PUT http://localhost:8000/api/v1/auth/change-password
Authorization: Bearer 12|nQ4GJ7zm9hV6TLSTdopX15xnGAs9GmErBGtALReH5440a6de
Content-Type: application/json
Accept: application/json

{
    "current_password": "admin123",
    "password": "NuevaPassword2026",
    "password_confirmation": "NuevaPassword2026"
}

### Actualizar Contraseña Inicial (Ruta correcta según tu api.php)
POST http://localhost:8000/api/v1/auth/update-initial-password
Authorization: Bearer 12|nQ4GJ7zm9hV6TLSTdopX15xnGAs9GmErBGtALReH5440a6de
Content-Type: application/json
Accept: application/json

{
    "password": "jugadordeunbit5011070",
    "password_confirmation": "jugadordeunbit5011070"
}

### Registro Maestro: Usuario + Persona + Rol
POST http://localhost:8000/api/v1/usuarios
Authorization: Bearer 12|nQ4GJ7zm9hV6TLSTdopX15xnGAs9GmErBGtALReH5440a6de
Content-Type: application/json

{
    "name": "juanita_perez",
    "email": "perez_v2@gmail.com",
    "password": "perez123",
    "password_confirmation": "perez123",
    "categoria_id": 1,
    "roles": [10],
    "persona": {
        "nombre_completo": "Juan Perez Segundo",
        "carnet_identidad": "99887766",
        "fecha_nacimiento": "1990-05-20",
        "genero": "M",
        "telefono": "72010020",
        "direccion":"b/mendez",
        "tipo_trabajador": "medico",
        "nacionalidad": "Boliviana",
        "tipo_salario": "TGN",
        "numero_tipo_salario": "4455"
    }
}


### Registro Maestro: Usuario + Persona + Rol
POST http://localhost:8000/api/v1/usuarios
Authorization: Bearer 13|1v9ffDibWG2GBqSzibhRIigdmhzGdUM6A4BIIgotd0ca48aa
Content-Type: application/json
Accept: application/json

{
    "name": "carmen rosa cari",
    "email": "carmenrosacari@gmail.com",
    "password": "carmenrosa123",
    "password_confirmation": "carmenrosa123",
    "categoria_id": 2,
    "roles": [11],
    "persona": {
        "nombre_completo": "Carmen Rosa Cari Figueroa",
        "carnet_identidad": "5011070",
        "fecha_nacimiento": "1990-05-20",
        "genero": "F",
        "telefono": "78708800",
        "direccion": "B/paraiso",
        "tipo_trabajador": "enfermera",
        "nacionalidad": "Boliviana",
        "tipo_salario": "TGN",
        "numero_tipo_salario": "5556"
    }
}

### Registro Maestro: Usuario + Persona + Rol
POST http://localhost:8000/api/v1/usuarios
Authorization: Bearer 13|1v9ffDibWG2GBqSzibhRIigdmhzGdUM6A4BIIgotd0ca48aa
Content-Type: application/json
Accept: application/json

{
    "name": "norma arias huarachi",
    "email": "normaariashuarachi@gmail.com",
    "password": "norma123",
    "password_confirmation": "norma123",
    "categoria_id": 1,
    "roles": [12],
    "persona": {
        "nombre_completo": "norma arias huarachi",
        "carnet_identidad": "5056891",
        "fecha_nacimiento": "1990-05-20",
        "genero": "F",
        "telefono": "78708881",
        "direccion": "B/paraiso",
        "tipo_trabajador": "administrativo",
        "nacionalidad": "Boliviana",
        "tipo_salario": "CONTRATO",
        "numero_tipo_salario": "78956"
    }
}